name: Terraform GitHub Actions
on:
  - push
jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2-beta
      - name: Install SOPS
        run: |
          wget https://github.com/mozilla/sops/releases/download/v3.5.0/sops_3.5.0_amd64.deb
          sudo dpkg -i ./sops_3.5.0_amd64.deb
          rm ./sops_3.5.0_amd64.deb
      - name: Decrypt Terraform Variables
        run: sops --decrypt --in-place ./main.auto.tfvars
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: Terraform Format
        uses: hashicorp/terraform-github-actions@v0.6.3
        with:
          tf_actions_version: 0.12.17
          tf_actions_subcommand: fmt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Terraform Init
        uses: hashicorp/terraform-github-actions@v0.6.3
        with:
          tf_actions_version: 0.12.17
          tf_actions_subcommand: init
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Terraform Validate
        uses: hashicorp/terraform-github-actions@v0.6.3
        with:
          tf_actions_version: 0.12.17
          tf_actions_subcommand: validate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Terraform Plan
        uses: hashicorp/terraform-github-actions@v0.6.3
        with:
          tf_actions_version: 0.12.17
          tf_actions_subcommand: plan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Terraform Apply
        uses: hashicorp/terraform-github-actions@v0.6.3
        with:
          tf_actions_version: 0.12.17
          tf_actions_subcommand: apply
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.ref == 'refs/heads/master'
      - name: Terraform State
        run: |
          git config user.name 'GitHub Actions'
          git config user.email 'support@github.com'
          git add ./terraform.tfstate
          git commit -sm 'feat(Terraform): State File' || true
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.ref == 'refs/heads/master'
