apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: $(CLUSTER_NAMESPACE)
spec:
  project: default
  source:
    repoURL: $(GIT_REPOSITORY)
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: $(CLUSTER_NAMESPACE)
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
